# Generated by Django 5.0.6 on 2024-06-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
